package com.lsstop.constant;

import java.util.Map;

/**
 * 表情常量
 *
 * @author lishusheng
 * @date 2026/2/15
 */
public class EmojiConst {

    private EmojiConst() {
    }

    /**
     * 表情映射：key为表情标记，value为表情图片URL
     */
    public static final Map<String, String> EMOJI_MAP = Map.<String, String>ofEntries(
            Map.entry("[微笑]", "https://www.staic.lsstop.cn/emoji/smile.gif"),
            Map.entry("[撇嘴]", "https://www.staic.lsstop.cn/emoji/pz.gif"),
            Map.entry("[色]", "https://www.staic.lsstop.cn/emoji/color.gif"),
            Map.entry("[发呆]", "https://www.staic.lsstop.cn/emoji/daze.gif"),
            Map.entry("[得意]", "https://www.staic.lsstop.cn/emoji/proud.gif"),
            Map.entry("[害羞]", "https://www.staic.lsstop.cn/emoji/shy.gif"),
            Map.entry("[闭嘴]", "https://www.staic.lsstop.cn/emoji/bz.gif"),
            Map.entry("[睡]", "https://www.staic.lsstop.cn/emoji/sleep.gif"),
            Map.entry("[大哭]", "https://www.staic.lsstop.cn/emoji/cry.gif"),
            Map.entry("[尴尬]", "https://www.staic.lsstop.cn/emoji/gg.gif"),
            Map.entry("[发怒]", "https://www.staic.lsstop.cn/emoji/rage.gif"),
            Map.entry("[调皮]", "https://www.staic.lsstop.cn/emoji/naughty.gif"),
            Map.entry("[呲牙]", "https://www.staic.lsstop.cn/emoji/cy.gif"),
            Map.entry("[惊讶]", "https://www.staic.lsstop.cn/emoji/jingya.gif"),
            Map.entry("[难过]", "https://www.staic.lsstop.cn/emoji/sad.gif"),
            Map.entry("[酷]", "https://www.staic.lsstop.cn/emoji/ku.gif"),
            Map.entry("[冷汗]", "https://www.staic.lsstop.cn/emoji/lenhan.gif"),
            Map.entry("[抓狂]", "https://www.staic.lsstop.cn/emoji/crazy.gif"),
            Map.entry("[吐]", "https://www.staic.lsstop.cn/emoji/tu.gif"),
            Map.entry("[偷笑]", "https://www.staic.lsstop.cn/emoji/touxiao.gif"),
            Map.entry("[可爱]", "https://www.staic.lsstop.cn/emoji/keai.gif"),
            Map.entry("[白眼]", "https://www.staic.lsstop.cn/emoji/baiyan.gif"),
            Map.entry("[傲慢]", "https://www.staic.lsstop.cn/emoji/aoman.gif"),
            Map.entry("[饥饿]", "https://www.staic.lsstop.cn/emoji/hunger.gif"),
            Map.entry("[困]", "https://www.staic.lsstop.cn/emoji/kun.gif"),
            Map.entry("[惊恐]", "https://www.staic.lsstop.cn/emoji/jingko.gif"),
            Map.entry("[流汗]", "https://www.staic.lsstop.cn/emoji/liuhan.gif"),
            Map.entry("[憨笑]", "https://www.staic.lsstop.cn/emoji/hanxiao.gif"),
            Map.entry("[悠闲]", "https://www.staic.lsstop.cn/emoji/youxian.gif"),
            Map.entry("[奋斗]", "https://www.staic.lsstop.cn/emoji/fendou.gif"),
            Map.entry("[咒骂]", "https://www.staic.lsstop.cn/emoji/zhouma.gif"),
            Map.entry("[疑问]", "https://www.staic.lsstop.cn/emoji/yiwen.gif"),
            Map.entry("[嘘]", "https://www.staic.lsstop.cn/emoji/xu.gif"),
            Map.entry("[晕]", "https://www.staic.lsstop.cn/emoji/yun.gif"),
            Map.entry("[折磨]", "https://www.staic.lsstop.cn/emoji/zhemo.gif"),
            Map.entry("[衰]", "https://www.staic.lsstop.cn/emoji/shuai.gif"),
            Map.entry("[骷髅]", "https://www.staic.lsstop.cn/emoji/kulou.gif"),
            Map.entry("[敲打]", "https://www.staic.lsstop.cn/emoji/qiaoda.gif"),
            Map.entry("[再见]", "https://www.staic.lsstop.cn/emoji/zaijian.gif"),
            Map.entry("[擦汗]", "https://www.staic.lsstop.cn/emoji/cahan.gif"),
            Map.entry("[抠鼻]", "https://www.staic.lsstop.cn/emoji/koubi.gif"),
            Map.entry("[鼓掌]", "https://www.staic.lsstop.cn/emoji/guzhang.gif"),
            Map.entry("[糗大了]", "https://www.staic.lsstop.cn/emoji/qiudale.gif"),
            Map.entry("[坏笑]", "https://www.staic.lsstop.cn/emoji/huaixiao.gif"),
            Map.entry("[左哼哼]", "https://www.staic.lsstop.cn/emoji/zhh.gif"),
            Map.entry("[右哼哼]", "https://www.staic.lsstop.cn/emoji/yhh.gif"),
            Map.entry("[哈欠]", "https://www.staic.lsstop.cn/emoji/haqian.gif"),
            Map.entry("[鄙视]", "https://www.staic.lsstop.cn/emoji/bishi.gif"),
            Map.entry("[委屈]", "https://www.staic.lsstop.cn/emoji/weiqu.gif"),
            Map.entry("[快哭了]", "https://www.staic.lsstop.cn/emoji/kuaikule.gif"),
            Map.entry("[阴险]", "https://www.staic.lsstop.cn/emoji/yinxian.gif"),
            Map.entry("[亲亲]", "https://www.staic.lsstop.cn/emoji/qinqin.gif"),
            Map.entry("[吓]", "https://www.staic.lsstop.cn/emoji/xia.gif"),
            Map.entry("[可怜]", "https://www.staic.lsstop.cn/emoji/kelian.gif"),
            Map.entry("[眨眼睛]", "https://www.staic.lsstop.cn/emoji/zhayanjing.gif"),
            Map.entry("[笑哭]", "https://www.staic.lsstop.cn/emoji/xiaoku.gif"),
            Map.entry("[doge]", "https://www.staic.lsstop.cn/emoji/doge.gif"),
            Map.entry("[泪奔]", "https://www.staic.lsstop.cn/emoji/leiben.gif"),
            Map.entry("[无奈]", "https://www.staic.lsstop.cn/emoji/wunai.gif"),
            Map.entry("[托腮]", "https://www.staic.lsstop.cn/emoji/tuosai.gif"),
            Map.entry("[卖萌]", "https://www.staic.lsstop.cn/emoji/maimeng.gif"),
            Map.entry("[斜眼笑]", "https://www.staic.lsstop.cn/emoji/xyx.gif"),
            Map.entry("[喷血]", "https://www.staic.lsstop.cn/emoji/px.gif"),
            Map.entry("[惊喜]", "https://www.staic.lsstop.cn/emoji/jx.gif"),
            Map.entry("[骚扰]", "https://www.staic.lsstop.cn/emoji/sr.gif"),
            Map.entry("[小纠结]", "https://www.staic.lsstop.cn/emoji/xjj.gif"),
            Map.entry("[我最美]", "https://www.staic.lsstop.cn/emoji/wzm.gif"),
            Map.entry("[加油抱抱]", "https://www.staic.lsstop.cn/emoji/jybb.gif"),
            Map.entry("[脑阔疼]", "https://www.staic.lsstop.cn/emoji/nkt.gif"),
            Map.entry("[沧桑]", "https://www.staic.lsstop.cn/emoji/cs.gif"),
            Map.entry("[捂脸]", "https://www.staic.lsstop.cn/emoji/wl.gif"),
            Map.entry("[辣眼睛]", "https://www.staic.lsstop.cn/emoji/lyj.gif"),
            Map.entry("[哦哟]", "https://www.staic.lsstop.cn/emoji/oy.gif"),
            Map.entry("[头秃]", "https://www.staic.lsstop.cn/emoji/tt.gif"),
            Map.entry("[问号脸]", "https://www.staic.lsstop.cn/emoji/whl.gif"),
            Map.entry("[暗中观察]", "https://www.staic.lsstop.cn/emoji/azgc.gif"),
            Map.entry("[emm]", "https://www.staic.lsstop.cn/emoji/emm.gif"),
            Map.entry("[吃瓜]", "https://www.staic.lsstop.cn/emoji/cg.gif"),
            Map.entry("[呵呵哒]", "https://www.staic.lsstop.cn/emoji/hhd.gif"),
            Map.entry("[无眼笑]", "https://www.staic.lsstop.cn/emoji/wyx.gif"),
            Map.entry("[狂笑]", "https://www.staic.lsstop.cn/emoji/kx.gif"),
            Map.entry("[面无表情]", "https://www.staic.lsstop.cn/emoji/mwbq.gif"),
            Map.entry("[加油]", "https://www.staic.lsstop.cn/emoji/jiayou.gif"),
            Map.entry("[魔鬼笑]", "https://www.staic.lsstop.cn/emoji/mgx.gif"),
            Map.entry("[拥抱]", "https://www.staic.lsstop.cn/emoji/yb.gif"),
            Map.entry("[爱心]", "https://www.staic.lsstop.cn/emoji/ax.gif"),
            Map.entry("[玫瑰]", "https://www.staic.lsstop.cn/emoji/mg.gif"),
            Map.entry("[凋谢]", "https://www.staic.lsstop.cn/emoji/dx.gif"),
            Map.entry("[幽灵]", "https://www.staic.lsstop.cn/emoji/yl.gif"),
            Map.entry("[爆筋]", "https://www.staic.lsstop.cn/emoji/bj.gif"),
            Map.entry("[示爱]", "https://www.staic.lsstop.cn/emoji/shiai.gif"),
            Map.entry("[心碎]", "https://www.staic.lsstop.cn/emoji/xs.gif"),
            Map.entry("[咖啡]", "https://www.staic.lsstop.cn/emoji/kf.gif"),
            Map.entry("[羊驼]", "https://www.staic.lsstop.cn/emoji/yt.gif"),
            Map.entry("[赞]", "https://www.staic.lsstop.cn/emoji/z.gif"),
            Map.entry("[握手]", "https://www.staic.lsstop.cn/emoji/ws.gif"),
            Map.entry("[胜利]", "https://www.staic.lsstop.cn/emoji/sl.gif"),
            Map.entry("[踩]", "https://www.staic.lsstop.cn/emoji/c.gif"),
            Map.entry("[点赞]", "https://www.staic.lsstop.cn/emoji/dz.gif"),
            Map.entry("[托脸]", "https://www.staic.lsstop.cn/emoji/tl.gif"),
            Map.entry("[拜托]", "https://www.staic.lsstop.cn/emoji/bt.gif"),
            Map.entry("[无聊]", "https://www.staic.lsstop.cn/emoji/wuliao.gif"),
            Map.entry("[我不看]", "https://www.staic.lsstop.cn/emoji/wbk.gif"),
            Map.entry("[飙泪]", "https://www.staic.lsstop.cn/emoji/bl.gif"),
            Map.entry("[害怕]", "https://www.staic.lsstop.cn/emoji/hp.gif"),
            Map.entry("[我酸了]", "https://www.staic.lsstop.cn/emoji/wsl.gif"),
            Map.entry("[月亮]", "https://www.staic.lsstop.cn/emoji/yueliang.gif"),
            Map.entry("[太阳]", "https://www.staic.lsstop.cn/emoji/ty.gif"),
            Map.entry("[猪头]", "https://www.staic.lsstop.cn/emoji/zt.gif"),
            Map.entry("[菜刀]", "https://www.staic.lsstop.cn/emoji/cd.gif"),
            Map.entry("[刀]", "https://www.staic.lsstop.cn/emoji/d.gif"),
            Map.entry("[啤酒]", "https://www.staic.lsstop.cn/emoji/pj.gif"),
            Map.entry("[茶]", "https://www.staic.lsstop.cn/emoji/cha.gif"),
            Map.entry("[大便]", "https://www.staic.lsstop.cn/emoji/db.gif"),
            Map.entry("[喝彩]", "https://www.staic.lsstop.cn/emoji/hc.gif"),
            Map.entry("[足球]", "https://www.staic.lsstop.cn/emoji/zq.gif"),
            Map.entry("[篮球]", "https://www.staic.lsstop.cn/emoji/lq.gif"),
            Map.entry("[棒棒糖]", "https://www.staic.lsstop.cn/emoji/bbt.gif"),
            Map.entry("[西瓜]", "https://www.staic.lsstop.cn/emoji/xg.gif")
    );
}
