spring.application.name=lsstop-server

# \u542F\u7528\u54EA\u4E2A\u914D\u7F6E\u6587\u4EF6
spring.profiles.active=dev

# \u65E5\u5FD7\u4E2D\u8F93\u51FA\u5168\u5C40HTTP\u8BF7\u6C42\u7F16\u53F7
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [requestId=%X{requestId:-}] [%thread] %logger{36} - %msg%n
